spring:
  application:
    name: eureka-server

server:
  port: 1001

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #表示是否将自己注册到Eureka Server，默认为true。由于当前这个应用就是Eureka Server，故而设为false。
    fetch-registry: true #表示是否从Eureka Server获取注册信息