spring:
  application:
    name: api-gataway
server:
  port: 5001

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: eureka-client
  add-host-header: true

eureka:
  client:
    service-url:
      defaultZone: http://peer1:1001/eureka/
